version: '3.1'

services:
  opportunity-backend:
    build: .
    container_name: opportunity-backend
    volumes:
      - ./media-local:/usr/app/media
      - ./config.yml:/usr/config.yml
    ports:
      - "8000:8000"
    networks:
      postgresdb:
        aliases:
          - backend

networks:
  postgresdb:
    external:
      name: pdb
